### ISSUE TITLE
Ubuntu 16.04 unit test error

### ISSUE THREAD

**Issue by stoiver** [GeoscienceAustralia/anuga_core#100]
With ubuntu 16.04 we observe a unit test error on test_sparse.py in method test_scalar_multiplication. 

Here is the error message

```
ERROR: Test method __rmul__
----------------------------------------------------------------------
Traceback (most recent call last):  
File "/home/user/anuga_core/build/testenv/lib/python2.7/site-packages/anuga/utilities/tests/test_sparse.py", line 142, in test_scalar_multiplication    
B = A*3  
File "/home/user/anuga_core/build/testenv/lib/python2.7/site-packages/anuga/utilities/sparse.py", line 122, in __mul__    
R = B*self  
File "/home/user/anuga_core/build/testenv/lib/python2.7/site-packages/anuga/utilities/sparse.py", line 73, in __getitem__    
i,j = key
TypeError: 'int' object is not iterable
```

**Comment by stoiver** [comment]
Fixed with PR #101
