### ISSUE TITLE
Error in Calculation of water flow 

### ISSUE THREAD

**Issue by TejuJ** [GeoscienceAustralia/anuga_core#127]
Hello 
   I am trying to calculate water flow at particular location so implemented 

file_sww=file_function('/mnt/i/anuga sample data examples/Rainfall_trial/sikkim_whole_test_wave_1.sww', output_centroids = True)
polyline = [[649807,3042993],[649914,3042937]]	
[Time,Q] = domain.get_flow_through_cross_section(file_sww, polyline) 

But getting following error
### Traceback (most recent call last):
  File "North_Sikkim.py", line 84, in <module>
    (Time,Q) = domain.get_flow_through_cross_section(file_sww, polyline)
  File "/usr/local/lib/python2.7/dist-packages/anuga/shallow_water/shallow_water_domain.py", line 1731, in get_flow_through_cross_section
    cross_section = Cross_section(self, polyline, verbose)
  File "/usr/local/lib/python2.7/dist-packages/anuga/shallow_water/forcing.py", line 719, in __init__
    verbose=self.verbose)
  File "/usr/local/lib/python2.7/dist-packages/anuga/abstract_2d_finite_volumes/generic_domain.py", line 415, in get_intersecting_segments
    return self.mesh.get_intersecting_segments(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/anuga/abstract_2d_finite_volumes/neighbour_mesh.py", line 1178, in get_intersecting_segments
    polyline = self.geo_reference.get_relative(polyline)
  File "/usr/local/lib/python2.7/dist-packages/anuga/coordinate_transforms/geo_reference.py", line 363, in get_relative
    points = ensure_numeric(points, num.float)
  File "/usr/local/lib/python2.7/dist-packages/anuga/utilities/numerical_tools.py", line 268, in ensure_numeric
    return num.ascontiguousarray(num.array(A, dtype=typecode, copy=False))
AttributeError: Interpolation_function instance has no attribute '__float__'

Regards,
Tejaswi

**Comment by stoiver** [comment]
Hi Tejaswi,


There are two versions of get_flow_through_cross_section, one as a member function of a domain and second working on an sww file. I think you want the second version.


SO you need something like


from anuga.shallow_water.sww_interrogate import get_flow_through_cross_section

file_sww='/mnt/i/anuga sample data examples/Rainfall_trial/sikkim_whole_test_wave_1.sww'

polyline = [[649807,3042993],[649914,3042937]]

Time, Q = get_flow_through_cross_section(file_sww, polyline)


Cheers

Steve


==============================
Stephen Roberts
Undergraduate Convenor
Mathematical Sciences Institute
Room 2005 P.A.P. Moran Building #26B
The Australian National University
Canberra, ACT 2601 AUSTRALIA
Ph: +61 2 61254445
CRICOS: 00120C

________________________________
