### ISSUE TITLE
Parallel ANUGA

### ISSUE THREAD

**Issue by wlai2014** [GeoscienceAustralia/anuga_core#148]
I also have more test on my laptop (intel I7 4 cores) with parallel ANUGA, for the runParallelCairns.py with shorter simulation time  (/anuga_core/examples/cairns), I used:
```
time mpirun -np XX python runParallelCairns.py > a.out
```
If XX = 1, 2, 4, it works, however, if XX = 3, it doesn't work.
```
XX = 1, it took 1min13s,
XX = 3, it took 2min18s,
XX = 4, it took 2min20s
```

I have another test channel3_parallel.py on my laptop with shorter simulation time (anuga_core/examples/simple_examples ):
```
mpirun -np XX python channel3_parallel.py > a.out
```
XX = 1, 2, 3 would work, while XX=4 sometimes works, sometimes doesn't.
```
XX = 1, it took 1min43s
XX = 2, it took 2min32s
XX = 3, it took 4min20s
XX = 4, it took 5min7s if it works.
```

**Comment by stoiver** [comment]
@wlai2014 I just ran the channel3_parallel.py example on my system (which is also intel i7 4 cores). 

On a fairly congested system, running 

time mpirun -np XX python channel3_parallel.py

I get "real time" as follows (note that "user time" will accumulate the cpu time from all the cores being used). 

XX = 1, it took 2min17s
XX = 2, it took 1min25s
XX = 3, it took 1min5s
XX = 4, it took 0min55s
XX = 5, it took 1min6s

So your results are surprising. Both the timing and the failures. What happens when "it doesn't work"?

**Comment by wlai2014** [comment]
@stoiver, thank you for your reply.  The results surprise me as well. 

For the cahnnel3_parallel.py case, for most time it work. When it doesn't work, sometimes it just show warning (2 different warnings as below),  or error:

Traceback (most recent call last):
  File "channel3_parallel.py", line 83, in <module>
    for t in domain.evolve(yieldstep=1, finaltime=10.0):
  File "/usr/local/lib/python2.7/dist-packages/anuga/shallow_water/shallow_water_domain.py", line 2421, in evolve
    self.initialise_storage()
  File "/usr/local/lib/python2.7/dist-packages/anuga/shallow_water/shallow_water_domain.py", line 2477, in initialise_storage
    self.writer.store_connectivity()
  File "/usr/local/lib/python2.7/dist-packages/anuga/file/sww.py", line 231, in store_connectivity
    self.writer.store_static_quantities(fid, **static_quantities)
  File "/usr/local/lib/python2.7/dist-packages/anuga/file/sww.py", line 886, in store_static_quantities
    outfile.variables[q][:] = x
KeyError: 'elevation'

or warning:

Traceback (most recent call last):
  File "channel3_parallel.py", line 83, in <module>
    for t in domain.evolve(yieldstep=1, finaltime=10.0):
  File "/usr/local/lib/python2.7/dist-packages/anuga/shallow_water/shallow_water_domain.py", line 2435, in evolve
    self.store_timestep()
  File "/usr/local/lib/python2.7/dist-packages/anuga/shallow_water/shallow_water_domain.py", line 2487, in store_timestep
    self.writer.store_timestep()
  File "/usr/local/lib/python2.7/dist-packages/anuga/file/sww.py", line 270, in store_timestep
    time = fid.variables['time'][:]
KeyError: 'time'

Here is the error I got from runParallelCairns.py
/usr/local/lib/python2.7/dist-packages/anuga/load_mesh/loadASCII.py:794: RuntimeWarning: invalid value encountered in greater
  mesh['vertices'] = fid.variables['vertices'][:]
/usr/local/lib/python2.7/dist-packages/anuga/load_mesh/loadASCII.py:794: RuntimeWarning: invalid value encountered in greater
  mesh['vertices'] = fid.variables['vertices'][:]
/usr/local/lib/python2.7/dist-packages/anuga/load_mesh/loadASCII.py:840: RuntimeWarning: invalid value encountered in greater
  mesh['points'] = fid.variables['points'][:]

Domain: Initialising
Pmesh_to_Domain: Initialising

Traceback (most recent call last):
  File "runParallelCairns.py", line 72, in <module>
    verbose=project.verbose)
  File "/usr/local/lib/python2.7/dist-packages/anuga/extras.py", line 162, in create_domain_from_regions
    args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/anuga/extras.py", line 205, in _create_domain_from_regions
    domain = Domain(mesh_filename, use_cache=False, verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/anuga/shallow_water/shallow_water_domain.py", line 218, in __init__
    ghost_layer_width=ghost_layer_width)
  File "/usr/local/lib/python2.7/dist-packages/anuga/abstract_2d_finite_volumes/generic_domain.py", line 97, in __init__
    verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/anuga/abstract_2d_finite_volumes/pmesh2domain.py", line 101, in pmesh_to_domain
    result = apply(_pmesh_to_domain, (file_name, mesh_instance))
  File "/usr/local/lib/python2.7/dist-packages/anuga/abstract_2d_finite_volumes/pmesh2domain.py", line 136, in _pmesh_to_domain
    tag_dict = pmesh_dict_to_tag_dict(mesh_dict)
  File "/usr/local/lib/python2.7/dist-packages/anuga/abstract_2d_finite_volumes/pmesh2domain.py", line 215, in pmesh_dict_to_tag_dict
    tag_dict = build_boundary_dictionary(triangles, segments, segment_tags, tag_dict)
RuntimeError: pmesh2domain.c: build_boundary_dictionary Duplicate segments


Thank you.
