### ISSUE TITLE
questions about the input file carins.asc

### ISSUE THREAD

**Issue by Dongxueyang** [GeoscienceAustralia/anuga_core#203]

**Comment by stoiver** [comment]
@Dongxueyang 

The -9999 represents "no value" or "not a number" and is excluded from the interpolation. 

Of course you can use a more complicated boundary. You can check some of the notebooks on https://github.com/stoiver/anuga-clinic-2018 in particular notebook1 and notebook2 to see the use of  `anuga.create_domain_from_regions`

**Comment by Dongxueyang** [comment]
@stoiver 
Thanks a lot. I will read the notebook carefully.
Another question.
I have finished computing carins example and run " python export_results_to_qgis.py"
But I got error like this:
Area of bounding polygon = 107720.35 km^2
output dir: cairns_fixed_wave
Traceback (most recent call last):
  File "export_results_to_qgis.py", line 30, in <module>   verbose=True)
  File "/usr/local/lib/python2.7/dist-packages/anuga/utilities/plot_utils.py", line 1004, in Make_Geotif
    raise ImportError, msg
ImportError: Failed to import gdal/ogr modules --perhaps gdal python interface is not installed.

And then I run "sudo apt-get install python-gdal" . But the error was not solved.
 dong

**Comment by Dongxueyang** [comment]
@stoiver 
If the iuput file .asc is not square, dx≠dy，can the anuga simulate successfully?

**Comment by Dongxueyang** [comment]
@stoiver 
Hi stoiver, I am run the example cairns_excel. But I got error like: Segmentation fault (core dumped).
So I want to change the resolution of the model. But I can not find the default_res.  I try to change the "maximum mesh triangle area" in file "cairns_excel" ,but it is useless . Could you help me how can I solve this problem?
best regards
dong

**Comment by stoiver** [comment]
@Dongxueyang i just tried to run the cairns_excel example and ran into a problem. I will look into it.

**Comment by stoiver** [comment]
@Dongxueyang, My problem was just that I forgot to unzip the cairns.zip file. 

Can you provide the `Simulation_logfile.log` file from your `cairns_excel` run. Should be in the appropriate `MODEL_OUTPUTS` directory.

**Comment by Dongxueyang** [comment]
I have unziped the cairns.zip file. But problem was not sovled, even I can not got file simulation_logfile.log.

**Comment by Dongxueyang** [comment]
@stoiver 
I have unziped the cairns.zip file. But I got the same error and even I can not get simulation_logfile.log.

**Comment by stoiver** [comment]
@Dongxueyang, so how have you installed anuga, on what type of machine, and have you successfully run the unit tests (via python runtests.py?).

**Comment by Dongxueyang** [comment]
@stoiver 
After I downloaded anuga. 
I ran "sudo sh install_ubuntu.sh" at anuga_core_master/tools .
And print follows on scream:

  InsecurePlatformWarning
install_ubuntu.sh: 78: install_ubuntu.sh: [[: not found
install_ubuntu.sh: 85: install_ubuntu.sh: [[: not found
install_ubuntu.sh: 92: install_ubuntu.sh: [[: not found
install_ubuntu.sh: 101: install_ubuntu.sh: [[: not found
install_ubuntu.sh: 101: install_ubuntu.sh: openmpi: not found
install_ubuntu.sh: 101: install_ubuntu.sh: openmpi: not found
+===============================================+
|  Build anuga                                  |
+===============================================+
python setup.py build
Building, see build.log...
Build OK

That took 0.501s
+===============================================+
|  Install anuga using setup.py                 |
+===============================================+
Running from anuga source directory.

There are some warnings but no errors.
And then I ran "python runtest.py"
I got this:

 Building, see build.log...
Build OK
Running unit tests for anuga
NumPy version 1.16.4
NumPy relaxed strides checking option: True
NumPy is installed in /usr/local/lib/python2.7/dist-packages/numpy
Python version 2.7.6 (default, Nov 13 2018, 12:45:42) [GCC 4.8.4]
nose version 1.3.7
....../usr/local/lib/python2.7/dist-packages/netCDF4/__init__.py:3: UserWarning: 
WARNING: Backwards incompatible files will be created with HDF5 1.10.x 
and netCDF < 4.4.1. Upgrading to netCDF4 >= 4.4.1 or downgrading to 
to HDF5 version 1.8.x is highly recommended 
(see https://github.com/Unidata/netcdf-c/issues/250).
  from ._netCDF4 import *
Segmentation fault (core dumped)

Maybe is the key of the problem. But I can run cairns example successfully. What is your opinion to this problem.

My computer is based on Ubuntu14.04 with python2.7.6, gcc4.8.4.

Best regards
dong

**Comment by stoiver** [comment]
@Dongxueyang, so there is some strange conflict between netcdf4 and hdf5. I wonder if your machine had anuga installed in the past?  Anyway there seems to be some conflict with what python expects and the netcdf4 library. 

It might be worth trying to install anuga within a conda environment. Checkout https://github.com/GeoscienceAustralia/anuga_core/wiki/Install-ANUGA-on-Ubuntu-(using-Miniconda)

Anyrate you need to get the unittests (via runtests.py ) working before expecting to get the examples to working consistently.

**Comment by Dongxueyang** [comment]
@stoiver 

Ok, I had not installed anuga in the past. 
 I will try again to install within conda environment later.
Thanks a lot.
dong

**Comment by Dongxueyang** [comment]
@stoiver 
Hi storiver, I want to set diffierent stage on diffierent areas in one model. Is it possible to achieve and is there an example with this function?
