### ISSUE TITLE
Problem Running Anuga with CUDA

### ISSUE THREAD

**Issue by budiaji** [GeoscienceAustralia/anuga_core#73]
Hi all,

I plan to use ANUGA with CUDA. I use this implementation of ANUGA-CUDA https://github.com/budiaji/anuga-cuda 

That implementation has two domain, gpu_domain_basic and gpu_domain_advanced. I can choose  which domain I use by modifying file https://github.com/budiaji/anuga-cuda/blob/master/src/anuga_cuda/__init__.py

I ran simple merimbula case here https://github.com/budiaji/anuga-cuda/blob/master/tests/CUDA/merimbula/merimbula.py

I am using anuga version 1.3.1. Using basic domain, the simulation ran fine. But using advanced domain I got this error:

```
Traceback (most recent call last):
  File "test_cuda_shallow_water.py", line 66, in <module>
    for t in domain.evolve(yieldstep = yieldstep, finaltime = finaltime):
  File "/home/somat/source/anuga-cuda/src/anuga_cuda/gpu_domain_advanced.py", line 2580, in evolve
    self.evolve_one_euler_step(yieldstep, self.finaltime)
  File "/home/somat/source/anuga-cuda/src/anuga_cuda/gpu_domain_advanced.py", line 2849, in check_point
    fn(*args, **kv)
  File "/home/somat/source/anuga-cuda/src/anuga_cuda/gpu_domain_advanced.py", line 2191, in evolve_one_euler_step
    self.update_timestep(yieldstep, finaltime)
  File "/home/somat/source/anuga-cuda/src/anuga_cuda/gpu_domain_advanced.py", line 2851, in check_point
    fn.original(self.cotesting_domain, *args, **kv)
  File "/home/somat/.virtualenvs/anuga-1.3.1/local/lib/python2.7/site-packages/anuga/abstract_2d_finite_volumes/generic_domain.py", line 2100, in update_timestep
    if self.get_time() + timestep > self.yieldtime:
AttributeError: CUDA_advanced_domain instance has no attribute 'yieldtime'
```

I thought that CUDA_advanced_domain class has no attribute yieldtime. I checked and it has attribute yieldtime. But somehow it's missing. 

Any ideas? Thank you.

**Comment by stoiver** [comment]
Hi,

The line numbers on your traceback don't seem to match the lines in the code on github. So a little hard to track down the problem. But it seems it has something to do with the cotesting domain. Do you get the error if you turn gpu off and leave cotesting on?

Can you check that the cotesting domain has the attribute yieldtime.

Cheers
Steve
